#!/bin/sh +e

install_keys() {
    X=0;
    while [ $(gpg --recv-keys 8B48AD6246925553; echo $?) -ne 0 ] && [ $X lt 10 ]; do
        X=$(($X+1))
    done
    X=0;
    while [ $(gpg --recv-keys 7638D0442B90D010; echo $?) -ne 0 ] && [ $X lt 10 ]; do
        X=$(($X+1))
    done
    X=0
    while [ $(gpg --recv-keys CBF8D6FD518E17E1; echo $?) -ne 0 ] && [ $X lt 10 ]; do
        X=$(($X+1))
    done
    gpg --export -a 8B48AD6246925553 | sudo apt-key add -
    gpg --export -a 7638D0442B90D010 | sudo apt-key add -
    gpg --export -a CBF8D6FD518E17E1 | sudo apt-key add -
}

upgrade_wheezy_to_jessie()
{
    [ -n "$1" ] || return 0

    ### update wheezy rpi to raspbian/jessie rpi, any rpi2 to debian/jessie
    case $1 in
      rpi)
        sed -i "s%deb[\ ]*http://mirrordirector.raspbian.org/raspbian.*wheezy%deb http://mirrordirector.raspbian.org/raspbian/ stable%g" /etc/apt/sources.list
        
        install_keys
        echo "!!!\nPlease upgrade packages again after this upgrade round\n!!!"

        sed -i 's/rpi-wheezy/rpi-jessie/g' /etc/apt/sources.list.d/xbian.list
        ;;
      rpi2)
        [ -e /etc/dpkg/origins/raspbian -a ! -e /etc/apt/sources.list.old.xbian.upgrade.jessie ] && \
            {
              mv /etc/apt/sources.list /etc/apt/sources.list.old.xbian.upgrade.jessie
              echo 'deb http://http.debian.net/debian stable main non-free' > /etc/apt/sources.list
            }

        sed -i 's/rpi-wheezy/rpi2-jessie/g' /etc/apt/sources.list.d/xbian.list
        install_keys
        echo "!!!\nPlease upgrade packages again after this upgrade round\n!!!"
        ;;
      *)
        ;;
    esac

}

if [ $1 = "configure" ]; then

    grep -q BCM2708 /proc/cpuinfo 2>/dev/null && config_platform=rpi
    grep -q BCM2836 /proc/cpuinfo 2>/dev/null && config_platform=rpi
    grep -q BCM2709 /proc/cpuinfo 2>/dev/null && config_platform=rpi2
    grep -q "i.MX6" /proc/cpuinfo 2>/dev/null && config_platform=imx6
    grep -q sun7i /proc/cpuinfo 2>/dev/null && config_platform=bpi
    grep -q 'rpi2\-jessie' /etc/apt/sources.list.d/xbian.list && config_platform=rpi2

    version="";
    if which lsb_release >/dev/null; then
        version=$(lsb_release -c -s);
    elif [ -f /etc/debian_version ]; then
        grep -q "7\..*" /etc/debian_version && version="wheezy"
        grep -q "8\..*" /etc/debian_version && version="jessie"
    else
        echo "could not determine running OS version"
    fi

    [ "$(xbian-arch 2>/dev/null)" = iMX6 -o "$config_platform" = imx6 ] && disrepos=devel || disrepos="staging devel"
    [ "$(xbian-arch 2>/dev/null)" = BPI -o "$config_platform" = bpi ] && disrepos=devel || disrepos="staging devel"

    for repo in stable staging devel; do
        if ! grep -q "$repo" /etc/apt/sources.list.d/xbian.list; then
            echo $disrepos | grep -q $repo && commentedout='### ' || commentedout=''
            echo "${commentedout}deb mirror://apt.xbian.org/mirror.txt     $repo   main    __ARCH__" >> /etc/apt/sources.list.d/xbian.list
        fi
    done

    if which xbian-arch >/dev/null && [ "$config_platform" != rpi2 ]; then
        sed -i "s%__ARCH__%$(xbian-arch | tr '[:upper:]' '[:lower:]')-$version%g" /etc/apt/sources.list.d/xbian.list
    else
        sed -i "s%__ARCH__%$config_platform-$version%g" /etc/apt/sources.list.d/xbian.list
    fi

    for k in /var/tmp/xbian.key/*.key; do 
        apt-key add $k
    done

    [ "$version" = wheezy ] || exit 0
    upgrade_wheezy_to_jessie $config_platform
fi
