#!/bin/sh

if [ $1 = "configure" ]; then

    grep -q BCM2708 /proc/cpuinfo 2>/dev/null && config_platform=rpi
    grep -q BCM2836 /proc/cpuinfo 2>/dev/null && config_platform=rpi
    grep -q "i.MX6" /proc/cpuinfo 2>/dev/null && config_platform=imx6
    grep -q sun7i /proc/cpuinfo 2>/dev/null && config_platform=bpi
    grep -q 'rpi2\-jessie' /etc/apt/sources.list.d/xbian.list && config_platform=rpi2

    version="";
    if which lsb_release >/dev/null; then
        version=$(lsb_release -c -s);
    elif [ -f /etc/debian_version ]; then
        grep -q "7\..*" /etc/debian_version && version="wheezy"
        grep -q "8\..*" /etc/debian_version && version="jessie"
    else
        echo "could not determine running OS version"
    fi

    [ "$(xbian-arch 2>/dev/null)" = iMX6 -o "$config_platform" = imx6 ] && disrepos=devel || disrepos="staging devel"
    [ "$(xbian-arch 2>/dev/null)" = BPI -o "$config_platform" = bpi ] && disrepos=devel || disrepos="staging devel"

    for repo in stable staging devel; do
        if ! grep -q "$repo" /etc/apt/sources.list.d/xbian.list; then
            echo $disrepos | grep -q $repo && commentedout='### ' || commentedout=''
            echo "${commentedout}deb mirror://apt.xbian.org/mirror.txt     $repo   main    __ARCH__" >> /etc/apt/sources.list.d/xbian.list
        fi
    done

    if which xbian-arch >/dev/null && [ $config_platform != rpi2 ]; then
        sed -i "s%__ARCH__%$(xbian-arch | tr '[:upper:]' '[:lower:]')-$version%g" /etc/apt/sources.list.d/xbian.list
    else
        sed -i "s%__ARCH__%$config_platform-$version%g" /etc/apt/sources.list.d/xbian.list
    fi

    for k in /var/tmp/xbian.key/*.key; do 
        apt-key add $k
    done
fi
