#!/bin/sh +e

install_keys() {
    X=0;
    while [ $(gpg --recv-keys 8B48AD6246925553; echo $?) -ne 0 ] && [ $X lt 10 ]; do
        X=$(($X+1))
    done
    X=0;
    while [ $(gpg --recv-keys 7638D0442B90D010; echo $?) -ne 0 ] && [ $X lt 10 ]; do
        X=$(($X+1))
    done
    X=0
    while [ $(gpg --recv-keys CBF8D6FD518E17E1; echo $?) -ne 0 ] && [ $X lt 10 ]; do
        X=$(($X+1))
    done
    gpg --export -a 8B48AD6246925553 | sudo apt-key add -
    gpg --export -a 7638D0442B90D010 | sudo apt-key add -
    gpg --export -a CBF8D6FD518E17E1 | sudo apt-key add -
}

modify_xbian_preferences()
{
    [ -n "$1" ] || return 0

    PF="/etc/apt/preferences.d/xbian"

    case $1 in
        imx6)
            if ! grep -q "Package.*openssl" $PF; then
                echo "" >> $PF
                echo "Package: openssl libssl1.0.0 irqbalance-imx" >> $PF
                echo "Pin: release o=XBian" >> $PF
                echo "Pin-Priority: 1001" >> $PF
            fi
            ;;
        *)
            ;;
    esac

}

upgrade_wheezy_to_jessie()
{
    [ -n "$1" ] || return 0

    ### update wheezy rpi to raspbian/jessie rpi, any rpi2 to debian/jessie
    case $1 in
      rpi)
        sed -i "s%deb[\ ]*http://mirrordirector.raspbian.org/raspbian.*wheezy%deb http://mirrordirector.raspbian.org/raspbian/ stable%g" /etc/apt/sources.list
        
        install_keys
        echo "!!!\nPlease upgrade packages again after this upgrade round\n!!!"

        sed -i 's/rpi-wheezy/rpi-jessie/g' /etc/apt/sources.list.d/xbian.list
        ;;
      rpi2)
        [ -e /etc/dpkg/origins/raspbian -a ! -e /etc/apt/sources.list.old.xbian.upgrade.jessie ] && \
            {
              mv /etc/apt/sources.list /etc/apt/sources.list.old.xbian.upgrade.jessie
              echo 'deb http://http.debian.net/debian stable main non-free' > /etc/apt/sources.list
            }

        sed -i 's/rpi-wheezy/rpi2-jessie/g' /etc/apt/sources.list.d/xbian.list
        install_keys
        echo "!!!\nPlease upgrade packages again after this upgrade round\n!!!"
        ;;
      *)
        ;;
    esac

}

if [ $1 = "configure" ]; then

    [ -x /usr/local/bin/xbian-arch ] && rm -rf /usr/local/bin/xbian-arch
    ln -s /usr/local/sbin/xbian-arch /usr/local/bin/xbian-arch

    config_platform=$(xbian-arch revision)
    version=$(xbian-arch os)
    [ $version != unknown ] || echo "could not determine running OS version"

    disrepos="staging devel"
    [ "$(xbian-arch 2>/dev/null)" = iMX6 -o "$config_platform" = imx6 ] && disrepos=devel
    [ "$(xbian-arch 2>/dev/null)" = BPI -o "$config_platform" = bpi ] && disrepos=devel

    repoarch="$(xbian-arch | tr '[:upper:]' '[:lower:]')"
    [ "$repoarch" = mvebu ] && repoarch=imx6

    if which xbian-arch >/dev/null && [ "$config_platform" != rpi2 ]; then
        repoarch=$repoarch-$version
    else
        repoarch=$config_platform-$version
    fi

    for repo in stable staging devel; do
        if ! grep -q "$repo" /etc/apt/sources.list.d/xbian.list; then
            echo $disrepos | grep -q $repo && commentedout='### ' || commentedout=''
            echo "${commentedout}deb mirror://apt.xbian.org/mirror.txt     $repo   main    __ARCH__" >> /etc/apt/sources.list.d/xbian.list
        elif ! grep -q "$repo.*$repoarch" /etc/apt/sources.list.d/xbian.list; then
            L=$(grep "$repo" /etc/apt/sources.list.d/xbian.list)
            sed -i "s%$L%$L    __ARCH__%g" /etc/apt/sources.list.d/xbian.list
        fi
    done

    sed -i "s%__ARCH__%$repoarch%g" /etc/apt/sources.list.d/xbian.list

    for k in /var/tmp/xbian.key/*.key; do 
        apt-key add $k
    done

    modify_xbian_preferences $config_platform

    [ "$version" = wheezy ] || exit 0
    upgrade_wheezy_to_jessie $config_platform
fi
