#!/bin/bash

# This is a workaround for preventing Kodi to crash while installing update(s)
# Under some conditions Kodi will crash when dpkg scripts are running command
# udevadm trigger ... (package pulseaudio does this)
if pgrep dpkg >/dev/null && pgrep "xbmc.bin|kodi.bin" >/dev/null && [ "$1" == trigger ]; then
    echo udevadm $@
    exit 0
fi
exec /sbin/udevadm $@
